### ISSUE TITLE
Click an item on the chart to get more info about that team

### ISSUE THREAD

**Issue by joshwnj** [joshwnj/team-index#19]
Might be useful to see an area chart for just this team, with breakdown of hours and members.  We should also provide a way to open the team's doc in the wiki editor.

**Comment by joshwnj** [comment]
This will be easy once #22 is implemented as we'll just need to set a hyperlink on chart elememts.

Looks relevant: http://api.highcharts.com/highcharts#plotOptions.series.point.events.click

**Comment by lfilho** [comment]
I'm on it
