### ISSUE TITLE
Reflect current wiki doc in the URL

### ISSUE THREAD

**Issue by joshwnj** [joshwnj/team-index#22]
This will allow:

- hyperlinking to a specific doc
- back-button

**Comment by lfilho** [comment]
I'm on it

**Comment by joshwnj** [comment]
Let me know what you're planning with this one, because I made a couple of changes to the route store (in the UI update) that might affect this.

**Comment by lfilho** [comment]
I haven't planned anything concrete yet, would just start revisiting the files, put the puzzles together in my head and see where to tackle it.
If you have advices / suggestions, I'm all ears :smile:

**Comment by joshwnj** [comment]
I think there are a couple of parts to this.  

- maybe we can attach a listener to the `route` store and update the location hash whenever it changes: https://github.com/joshwnj/team-index/blob/master/frontend/main.js#L32
- we can also use an `onhashchanged` event to handle the case of user arriving at a doc via hyperlink or using back-button
- we'll also need to update the routing to use a regex like `/wiki/:docId`.  At the moment it's just doing a string match: https://github.com/joshwnj/team-index/blob/master/frontend/components/main-content.js#L23-L26

**Comment by lfilho** [comment]
Thanks for the tips. Will look into them shortly
