### ISSUE TITLE
Update wiki UI

### ISSUE THREAD

**Issue by joshwnj** [joshwnj/team-index#34]
A couple of aspects of the wiki UI have been bugging me, and I think part of it is that I set out to use the same form for loading + creating + editing.

Also, there is the use-case of browsing the wiki, reading and following wikilinks (without necessarily wanting to making changes) that is not really covered at the moment. For this reason I think we should make the default view show only the Preview, and reveal edit fields as needed.

Some ideas on what to try next:
- default view (showing the Preview of the current doc, and a single field to load a new doc): http://screencast.com/t/RUJ2rkULw
- after clicking Edit: http://screencast.com/t/2h9viVvXJGGo
- after clicking Load and not finding an existing doc: http://screencast.com/t/ENB8yqp9vRk3

@lfilho let me know what you think about this. I'm hoping it creates *less* edge-cases for us, rather than more :)

**Comment by lfilho** [comment]
- :+1: for this. I think this way would be easier to use.
- On the "- Choose a Type -"  dropdown (Create a doc screenshot), how would we enter a new Type?
- I think having the preview side-by-side was a better idea... Seems like we won't have too much data in the bodies (or will we?), so I think it's nice to use that extra blank space for side-by-side preview... Thoughts?
- Minor wording suggestion: while editing, instead of "close": "cancel" button? 
- Ultra minor wording suggestion: "Load" feels to me that we know for sure there is something to be loaded (which is not always the case). So "Search" feels more correct to me (as in: "Search and if not found create"). Did that make sense?

**Comment by joshwnj** [comment]
Great feedback, thanks. 

- for the Type dropdown, I think we can get away with hardcoding available types in the frontend for now. As far as the backend knows/cares it is still just an arbitrary string, but hardcoding the available types on the frontend will just be 1 less thing for new users to learn.

- I agree side-by-side editor & preview can be cool at times.  The current version is already set up so that it goes side-by-side when there is room, and stacks vertically for smaller windows. So yeah I think we can keep it like that.  Eventually we probably want to allow user to customize widths and remember their settings in localstorage.

- yeah I was going back and forth with "Close" and "Cancel". I guess Cancel is more standard, so let's start with that and just confirm it fits every case.

- Great suggestion to rename "Load" to "Search".  You actually reminded me of something I forgot to include in the mockup: when you Search for a doc and it's not found, we'll show the "Create a doc" form and we'll _also_ show top 5 search results for that ID, in case you were looking for an existing doc but mistyped it.

I'll update the mockups and commit them

**Comment by joshwnj** [comment]
I've updated the mockup, you can pull from master and open this file: https://github.com/joshwnj/team-index/blob/master/docs/ui-mockup/index.html

Then follow the instructions in the js console to load the different screens (edit and search)

**Comment by joshwnj** [comment]
status: main updates are done, just fixing a couple of little bugs before I push.

**Comment by lfilho** [comment]
Awesome! Just saw it superficially for now but liked what I saw (in terms of code as well - the rpc thing really simplified things on the http layer. Easier to digest I guess... Good work

**Comment by joshwnj** [comment]
Pushed some updates just now.  Finally we'll do a review of functionality before closing this issue.

**Comment by joshwnj** [comment]
Completed in https://github.com/joshwnj/team-index/commit/dcfbb2a5c76a1b7d8d77c8061b5d10328dca885f
