### ISSUE TITLE
Textarea from old doc stays open when you browse to a new doc

### ISSUE THREAD

**Issue by joshwnj** [joshwnj/team-index#42]
When you browse to a new doc it should exit "Edit" mode first.

**Comment by lfilho** [comment]
I'm on it

**Comment by lfilho** [comment]
@joshwnj I'm not being able to reproduce this. Could detail the steps a bit more?
Maybe my recent changes fixed this as a side effect... try giving my PRs a go and see if the problem persists...

Thx

**Comment by joshwnj** [comment]
You're right, looks to be fixed! Thanks

**Comment by lfilho** [comment]
Great!
