### ISSUE TITLE
Wiki doc sometimes fails to load

### ISSUE THREAD

**Issue by joshwnj** [joshwnj/team-index#44]
To reproduce:
- browse to a doc
- browse to dashboard
- press Back button to return to doc

Expect: doc to load
Actual: displays "..loading.." message.

**Comment by joshwnj** [comment]
Turns out this was because we had `loading: true` in `getInitialState`, and because the doc was already in the store when we return to it, the expected lifecycle functions weren't being triggered to take us out of `loading` state.

**Comment by lfilho** [comment]
I think we now have a side effect: i'm not able to create new docs anymore.

1. Search for a non-existing id "foobar123" 
2. Displays "..loading (foobar123).."

**Comment by lfilho** [comment]
Proposed fix on #47
